### ISSUE TITLE
Message loss

### ISSUE THREAD

**Issue by yurivict** [Bitmessage/PyBitmessage#723] opened 2014-10-05 21:15 UTC
I am experiencing the message loss. Some messages never arrive, and some acknowledgements never arrive.

Particularly, I am testing with one account in the clear internet, and another account inside the tor-connected system (UDP doesn't work). Message loss is between the two.

I don't know how to emphasize this enough, but this problem is a deal breaker for many/most people. Message loss should absolutely not exist.

**Comment by PeterSurda** [comment] 2015-10-18 11:13
Occasionally, it may take a while for the message to arrive. Can you confirm that they NEVER arrive, rather than merely being delayed?

**Comment by yurivict** [comment] 2015-10-18 19:53
At the time when I observed this, I definitely observed the loss, and not the delay, on multiple occasions. This has been confirmed by my contacts. This is why I had to abandon BM at the time.

(IMO you need to make another release to encourage people to try the new code and use BM more. Last release was over a year ago.)

**Comment by mailchuck** [comment] 2015-10-18 20:02
Would you be willing to help with testing? I don't have any tor setup. I created a new address for this bug, BM-2cWNJcPxLsjKtQ9Hu3XD5Ev4TVQ4QX3jkC. You can just create a new address and send me something.

I do have plan for a new release and approximate list of things I would like to have there. You can look at [Milestone 0.6](https://github.com/Bitmessage/PyBitmessage/milestones/v0.6.0), which I created just today. I can't promise anything yet, but I hope it will be by the end of the year.

**Comment by yurivict** [comment] 2015-10-18 20:17
Ok, I will send you 10 messages from the tor-connected system and will see if you get all 10.

**Comment by mailchuck** [comment] 2015-10-18 20:37
You know, there is something that comes to my mind. In the past, including the latest official release, 0.4.4, PyBitmessage treated messages with identical subject and body as duplicates, even if they were sent separately. There is an issue for that,  #748, and Atheros fixed this in https://github.com/Bitmessage/PyBitmessage/commit/95c939a2a06a6098199f6fad208d355bc93ef402 . 

This was a very insidious issue, because, precisely as you describe, messages mysteriously do not arrive. They actually do arrive, but the recipient's PyBitmessage thinks it's a duplicate and ignores it, so to the user it appears never to arrive.

If that's the case, then getting the latest source from master branch will fix it. My development fork, https://github.com/mailchuck/PyBitmessage, also has this patch, and other enhancements.

**Comment by mailchuck** [comment] 2015-10-18 20:38
Also note, in this particular bug, it is the recipient that needs to upgrade, the sender does not have to.

**Comment by yurivict** [comment] 2015-10-18 20:48
Ok, I am sending all different subjects now. I don't remember if the subjects were all the same when I originally observed the problem. This could have easily been the case.

**Comment by mailchuck** [comment] 2015-10-18 20:49
Yes, that sounds like it. So far I got the first five and replied to all.

**Comment by mailchuck** [comment] 2015-10-18 20:51
If I recall correctly, it also caused the acknowledgement to not be sent either, so to the sender it also looked like the recipient never received anything.

**Comment by mailchuck** [comment] 2015-10-18 21:49
I got all 10 now and responded to all, and got acks for all as well.

**Comment by yurivict** [comment] 2015-10-18 21:53
Ok, so it looks like all 10 messages went through.

Maybe this was really triggered by the subject sameness. Feel free to close it. If someone can spot the problem, they can re-open it.

**Comment by PeterSurda** [comment] 2015-10-19 10:28
Probably a duplicate of #748 and fixed in #783. If you are still experiencing message loss, make sure to use either latest master (newer than the stable release 0.4.4) or the [Mailchuck fork](https://github.com/mailchuck/PyBitmessage). Fix be a part of the next stable release.

**Closed by PeterSurda** 2015-10-19 10:28 UTC
