### ISSUE TITLE
BM uses too much memory: process size is almost 1GB.

### ISSUE THREAD

**Issue by yurivict** [Bitmessage/PyBitmessage#870] opened 2016-06-09 17:40 UTC
After a while the process size grows to 960MB for me. This is too much for a communication program. DB size is 75MB (messages.dat).

**Comment by PeterSurda** [comment] 2016-06-09 17:44
What OS, what python version, what openssl version?

**Comment by yurivict** [comment] 2016-06-09 18:13
FreeBSD 10.3 amd64, python27-2.7.11
OpenSSL 1.0.1t-freebsd  3 May 2016

**Comment by PeterSurda** [comment] 2016-06-09 18:14
Ok, give me some time to check it out.

**Comment by PeterSurda** [comment] 2016-06-13 20:22
I'm sorry, I can't reproduce this. I kept the latest v0.6 branch running on a FreeBSD VM for about 3 days now, and I get VSZ: 498M, RSS: 197M. This looks similar to what other programs have (for example, both variables are about half of what gnome-shell consumes. The VM is only running a gnome-terminal with 3 tabs and PyBitmessage. Can you provide more details, or compare it to other programs on your machine?

**Comment by yurivict** [comment] 2016-06-13 20:54
I have VSZ=918M RSS=341M, BM has ~30 chan subscriptions, but only one is active.

As a comparison: zeronet 225MB/105MB, qtox 577MB/85MB, firefox with 4 pages open 1006MB/568MB.

So BM is like firefox with 4 pages open memory-wise, but BM only shows a few static and small message boxes. It seems excessive to me, but maybe it's just the way python works, not sure.

I am closing this for now.

**Comment by bmng-dev** [comment] 2016-06-14 06:05
This is related to the stack size of threads. A new install on Tails shows 737 MiB of virtual memory at the 'Bitmessage won't connect to anyone until you let it' dialog. If I change the number of outgoingSynSender threads to 1 in the code and launch PyBitmessage again the virtual memory has dropped to 232.7 MiB.

`cat /proc/$PID/maps | grep -F '[stack'` in the first case listed 74 8188KiB ranges, while the second case showed just 11. 

The use of outgoingSynSender threads needs to be reconsidered; at the very least only create and start 8 whenever a new outgoing connection is required and stop those 8 when a connection is established.

The next thing to consider is when accepting incoming connections. There is a limit of 220 and 3 threads (class_receiveDataThread, class_sendDataThread, class_objectHashHolder) are created for each connection meaning at full capacity PyBitmessage would have about ~5.15 GiB of stack space. 

This certainly seems like a negative side effect for #270 although obviously the impact will vary depending on OS and default stack size.

**Comment by yurivict** [comment] 2016-06-14 06:22
This is a bad idea to create many threads per connection in the program like BM which doesn't consume much CPU. My BM process use 131 (!!!) threads. Threads become an overhead. One thread should be enough to service all connections in a loop. Maybe gevent (http://www.gevent.org) can be used?

VSZ part is also pushed by peak memory allocations, because the memory libraries don't really release the memory to OS (unmap) when released by the program.

**Comment by PeterSurda** [comment] 2016-06-14 10:16
I thought that threads are supposed to be a lightweight mechanism. Or is this something that is caused by python's GIL?

**Comment by yurivict** [comment] 2016-06-14 19:54
Threads become an overhead when all they do is serve one light network connection. I hit this problem a few times, including at $JOB. A typical mistake is to create one thread per connection when there are a lot of them, like in BM. You may also run out of resources on some systems.

A better approach is to have a single select(2) or kqueue(2) (in BSD) loop in one thread. I think gevent library is doing this nicely for python, but I didn't use it myself. In BM, separate threads would make sense for POW, for example. Other things should be done in one thread IMO.

**Comment by PeterSurda** [comment] 2016-08-14 10:50
I have reviewed this, and I plan to change the threading networking model into asyncore. But I want to have 0.6.1 out first with accumulated bugfixes.

**Comment by PeterSurda** [comment] 2016-08-15 18:08
After further investigation, I'll probably do tests both with asyncore (select) and gevent (multiple methods including kqueue/epoll) to make sure the work fine on all systems, and then I'll decide which of those two to use. Gevent has its own SSL support, which would be great to get rid of the problems with python's ssl library, in particular the inability to use TLS server mode with < 2.7.9. I found an asyncore TLS handshaker but it seems to use python's native ssl library, so on one hand it won't be able to work around the bugs but shouldn't introduce new ones either.

**Comment by PeterSurda** [comment] 2016-10-23 20:13
Progress report: I decided to try asyncore first, because it's already a part of python and there is no need to install an additional package like gevent. I made a couple of classes to test a SSL server and client, and it seems to work fine. It's not as fast as if I did it in C, but I think it's going to work out fine. Unless I find some weird issues, I'll keep asyncore.

**Comment by Rav3nPL** [comment] 2017-04-04 16:20
It is also present 0.6.2 windows version.
Looks for me, it is aok when no incomming connections. After I delete knownnodes.dat it consumes "nomal" amount of RAM. When connection indicator switch from yellow to green - memory is eaten.

**Comment by PeterSurda** [comment] 2017-05-29 13:58
The latest code in v0.6 branch has been moved to asyncore. There are some minor things missing, but for testing it should be fine. There are also development snapshots (20170529) for Windows and OSX: https://bitmessage.org/download/snapshots/. Please let me know if it's working better. I haven't tested it on FreeBSD yet, but I did on linux, Windows an OSX so it will probably work too.

**Comment by PeterSurda** [comment] 2017-10-16 17:20
So, I'm mostly happy with how it works now. There's still the randomly occurring recursion bug I can't figure out, but I think the memory usage is now under control and the UI lag appears to be fixed too. kqueue support is broken but I'll fix that soon (if you manually change the poller to poll or select, it works on bsd). The memory requirements still scale (about linearly) with the number of active connections but it's much better now. I currently have 179 connections and the process needs 1.214GB RAM. I think I'm close to the limit of what can be improved without significant redesign. Perhaps I can fiddle around with garbage collection to make sure there is less unreleased memory but I don't expect much out of it.

**Comment by PeterSurda** [comment] 2018-01-02 21:29
I could use help with fixing kqueue poller (OSX, FreeBSD, ...)

**Comment by PeterSurda** [comment] 2018-01-31 21:29
kqueue poller fixed in d223bfc6f29367b7d70e35f7bf1185a7bc3ca239

**Closed by PeterSurda** 2018-01-31 21:29 UTC
Labels: bug
