### ISSUE TITLE
Conversation Threads

### ISSUE THREAD

**Issue by Deathsbreed** [Bitmessage/PyBitmessage#994] opened 2017-05-06 12:08 UTC
Something I enjoy about e-mail (or rather, my e-mail client) is the ability for conversations to be threaded, making long conversations with many branches easy to follow. It would be nice if Bitmessage had something similar in one way or another making long conversations on chans (for example) easier to follow, grouping them based on which message exactly the other person is responding to.

**Comment by PeterSurda** [comment] 2017-05-07 18:13
Duplicate of #839

**Closed by PeterSurda** 2017-05-07 18:13 UTC
Labels: duplicate
