### ISSUE TITLE
Inbox message textbox retains formatting

### ISSUE THREAD

**Issue by nimdahk** [Bitmessage/PyBitmessage#248] opened 2013-06-23 06:00 UTC
After viewing a message as HTML which changes the font via a style tag, and clicking in the text which is altered, subsequent messages viewed will retain the style.

sample:

&lt;html>
&lt;style type="text/css"> 
    #header { font-size: 12px; color: #555; } 
&lt;/style>
&lt;div id="header">Click here, then view another message&lt;/div>

**Comment by PeterSurda** [comment] 2015-11-10 17:42
Duplicate of mailchuck#106.

**Comment by PeterSurda** [comment] 2015-11-10 23:53
Fixed in https://github.com/mailchuck/PyBitmessage/commit/78734d81a17bcd3672db6fc764b380c2813634d4

**Closed by PeterSurda** 2015-11-10 23:53 UTC
Labels: bug
