### ISSUE TITLE
bitmessage dont start up any more when database too large or related

### ISSUE THREAD

**Issue by subscribernamegoeshere** [Bitmessage/PyBitmessage#524] opened 2013-10-11 17:55 UTC
memory overflow at 1.79gigabytes ram consumption on windows 32bit machine running provided latest win32 binary of bitmessage.exe

bitmessage.exe recently crashed during runtime with qt4...dll gui or similar, and now never starts up any more in the end, as it crashes with unknown memory error whenever it is started up now and taskmanager and other process related tools show that its memory consumption grows up til exactly right below 1.8gigs of ram then it gives this crash. reproducable.

some days ago I think there was a post on the general channel public shared address list talking exactly about this phenomenon back then already

apparently now its happening for me.

bitmessage must not read the total database and keep too many objects in ram, but should only read the database if needed and not store too many objects in ram.

**Comment by PeterSurda** [comment] 2015-10-18 10:33
Try my fork which has a better UI: https://github.com/mailchuck/PyBitmessage. Now each account, subscription and channel have their own list, and you can switch among them in a tree. If the large amount of subscriptions is the cause of your problems, this should make it better, possible even fix it. I plan to merge this UI to main pybitmessage by next stable release. Let me know how it worked out.

**Comment by mailchuck** [comment] 2015-10-29 16:24
@subscribernamegoeshere Can you try [the latest release from my fork](https://github.com/mailchuck/PyBitmessage/releases/tag/v0.5.0)?
 There is a good chance it will help.

**Comment by PeterSurda** [comment] 2015-11-11 22:54
Well I got no feedback so I'm closing it. If you need a Win32 executable, let me know and I'll figure something out (I haven't figured out how to install both 32bit and 64bit qt at the same time and this prevents me from being able to create a Win32 bundle).

**Closed by PeterSurda** 2015-11-11 22:54 UTC
Labels: bug

**Comment by PeterSurda** [comment] 2015-11-26 17:16
@subscribernamegoeshere Just a small note, the 0.5.4 binary of mailchuck fork is built for 32bit, and people reported that it works on XP. You may want to try it out.
