### ISSUE TITLE
ERROR - Could not find any typelib for MessagingMenu

### ISSUE THREAD

**Issue by benpl** [Bitmessage/PyBitmessage#706] opened 2014-08-15 09:34 UTC
pyBM will throw:
**ERROR - Could not find any typelib for MessagingMenu**
I have installed on my system all needed dependencies and I also run update PyBitmessage from source. Error under Ubuntu 14.04 and Elementary OS Luna.

[From terminal:]
```
benpl@benpl-comp:~$ cd PyBitmessage/ && python src/bitmessagemain.py
Loading existing config files from /home/benpl/.config/PyBitmessage/
2014-08-15 11:00:01,686 - DEBUG - Database file already exists.
Could not read the Namecoin config file probably because you don't have Namecoin installed. That's ok; we don't really need it. Detailed error message: [Errno 2] No such file or directory: '/home/benpl/.namecoin/namecoin.conf'
2014-08-15 11:00:01,883 - DEBUG - Loaded 0 objects from disk into the objectProcessorQueue.
2014-08-15 11:00:01,883 - DEBUG - reloading keys from keys.dat file
2014-08-15 11:00:02,008 - DEBUG - reloading subscriptions...
An Exception occurred within isOurOperatingSystemLimitedToHavingVeryFewHalfOpenConnections: invalid version number '#101-Ubuntu SMP Tue Jul 15 17:46:11 UTC 2014'
2014-08-15 11:00:02,064 - ERROR - Could not find any typelib for MessagingMenu
Traceback (most recent call last):
  File "src/bitmessagemain.py", line 272, in <module>
    mainprogram.start()
  File "src/bitmessagemain.py", line 239, in start
    bitmessageqt.run()
  File "/home/benpl/PyBitmessage/src/bitmessageqt/__init__.py", line 3812, in run
    myapp = MyForm()
  File "/home/benpl/PyBitmessage/src/bitmessageqt/__init__.py", line 577, in __init__
    l10n.formatTimestamp()))
  File "/home/benpl/PyBitmessage/src/l10n.py", line 60, in formatTimestamp
    return unicode(timestring, encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 2: ordinal not in range(128)
```

**Comment by PeterSurda** [comment] 2015-11-11 00:37
I cannot reproduce this on https://github.com/mailchuck/PyBitmessage, I think it was fixed in 111d60dde89f866e525684789884e69b3f944d91. I tried German, French and Polish, both UTF-8 and ISO-8859-1/ISO-8859-2 and it works fine (there's no polish translation but it doesn't crash). When I revert the aforementioned commit, it crashes exactly as you describe. I have Ubuntu 14.04. Please reopen if you still experience this problem.

**Closed by PeterSurda** 2015-11-11 00:37 UTC
Labels: bug
