### ISSUE TITLE
I can't send to a mailing list if I'm hosting it

### ISSUE THREAD

**Issue by grant-olson** [Bitmessage/PyBitmessage#402] opened 2013-08-12 20:40 UTC
This is probably similar to #239 but the case is a little different.

1. I'm hosting a mailing list.

1. I tried to reply to someone else's post.

1. My send hangs with the text "Waiting on their encryption key.  Will request it again soon.

I don't so much care if the original message hits the peer-to-peer network, but it would be nice to be able to reply without having to use a different bitmessage instance and/or fake out the reply by sending a broadcast.

**Comment by PeterSurda** [comment] 2015-11-27 14:04
I can't reproduce it in the UI, it was probably fixed in https://github.com/mailchuck/PyBitmessage/commit/ceeea1da732eb02f15bdd4287a3cfc804227693f, or slightly later, because I remember that broadcasts didn't work at the beginning of my changes.

It may still not work when using the API though, in this case, it is supposed to send a broadcast rather than a normal message. So it actually probably is a frontend issue and not an API issue. The API doesn't magically know that when you call sendMessage it is actually supposed to send a broadcast instead. What are you using as a frontend, or perhaps what were you using at a frontend when you encountered this?

**Comment by PeterSurda** [comment] 2015-12-11 22:53
Sorry decided that this is a frontend issue and there's nothing for me to fix here.

**Closed by PeterSurda** 2015-12-11 22:53 UTC
Labels: wontfix
