### ISSUE TITLE
Language menu lists Espanol, but we don't have any Spanish translations

### ISSUE THREAD

**Issue by grant-olson** [Bitmessage/PyBitmessage#514] opened 2013-09-27 13:57 UTC
```
aster-blaster:PyBitmessage grant$ ls -al src/translations/
total 1368
drwxrwxr-x  17 grant  staff    578 Sep 26 10:10 .
drwxrwxr-x  63 grant  staff   2142 Sep 27 09:49 ..
-rw-rw-r--   1 grant  staff    960 Sep 26 10:10 bitmessage_de.pro
-rw-rw-r--   1 grant  staff  62134 Sep 26 10:10 bitmessage_de.qm
-rw-rw-r--   1 grant  staff  83162 Sep 26 10:10 bitmessage_de.ts
-rw-rw-r--   1 grant  staff    963 Sep 26 10:10 bitmessage_en_pirate.pro
-rw-rw-r--   1 grant  staff  17397 Sep 26 10:10 bitmessage_en_pirate.qm
-rw-rw-r--   1 grant  staff  72715 Sep 26 10:10 bitmessage_en_pirate.ts
-rw-rw-r--   1 grant  staff    960 Sep 26 10:10 bitmessage_eo.pro
-rw-rw-r--   1 grant  staff  42295 Sep 26 10:10 bitmessage_eo.qm
-rw-rw-r--   1 grant  staff  82027 Sep 26 10:10 bitmessage_eo.ts
-rw-rw-r--   1 grant  staff    960 Sep 26 10:10 bitmessage_fr.pro
-rw-rw-r--   1 grant  staff  49460 Sep 26 10:10 bitmessage_fr.qm
-rw-rw-r--   1 grant  staff  84682 Sep 26 10:10 bitmessage_fr.ts
-rw-rw-r--   1 grant  staff    960 Sep 26 10:10 bitmessage_ru.pro
-rw-rw-r--   1 grant  staff  60311 Sep 26 10:10 bitmessage_ru.qm
-rw-rw-r--   1 grant  staff  99746 Sep 26 10:10 bitmessage_ru.ts
```

**Comment by PeterSurda** [comment] 2015-10-18 10:37
I'll test this.

**Comment by PeterSurda** [comment] 2015-11-11 00:40
I can still reproduce it on the Windows release.

**Comment by PeterSurda** [comment] 2015-11-11 00:41
@Ryuno-Ki That's odd, it seems to work fine on linux for me. Can you try on the latest stable release, or the https://github.com/mailchuck/PyBitmessage fork?

**Comment by PeterSurda** [comment] 2015-11-11 01:49
It looks like @Atheros1 did fix it in the code, but the pyinstaller spec file needs to be modified manually as described here: https://bitmessage.org/wiki/Example_pyinstaller_spec_file. I updated my spec file and that fixes it. Future Windows releases will include localisation.

OSX bundle has the opposite problem, the files are included, but the code does not look in the correct directory. I fixed that in https://github.com/mailchuck/PyBitmessage/commit/df54bbad81d4b2fa1b419d848432a0969d234e2c.

If on linux, if you use a custom installation script that puts the translations in a separate tree, the translations maybe wouldn't work. @Ryuno-Ki, can you explain how exactly you run it? Do you just download/git-pull it and then run from there or do you run some sort of installation script?

**Comment by PeterSurda** [comment] 2015-11-11 08:30
I'm closing this. If you still encounter this with the latest https://github.com/mailchuck/PyBitmessage/ (on linux) or after 0.5.3 (Windows/OSX binaries), let me know.

**Closed by PeterSurda** 2015-11-11 08:30 UTC
Labels: bug
